In [2]:
print('hello')

hello

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
df = pd.read_csv('tested.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
df.drop(columns=['Pclass','PassengerId', 'Name', 'Ticket', 'Cabin','SibSp','Ticket','Parch','Sex','Embarked'],inplace = True)
df.head()

   Survived   Age     Fare
0         0  34.5   7.8292
1         1  47.0   7.0000
2         0  62.0   9.6875
3         0  27.0   8.6625
4         1  22.0  12.2875

In [8]:
df.isnull().sum()

Survived     0
Age         86
Fare         1
dtype: int64

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

In [10]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [11]:
x = df[['Age','Fare']]
y = df['Survived']

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=24)

In [13]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [14]:
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test_scaled)

In [15]:
accuracy = accuracy_score(y_test,y_pred)
confusion_matrix = confusion_matrix(y_test,y_pred)
print(accuracy)
print(confusion_matrix)

0.6071428571428571
[[51  0]
 [33  0]]

In [16]:
single_n = Sequential(
    [Dense(1, input_dim = 2, activation = 'sigmoid')])

In [17]:
single_n.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy'])

In [18]:
history = single_n.fit(
    x_train_scaled,
    y_train,
    epochs = 500,
    batch_size = 64,
    verbose = 1
)

Epoch 1/500
6/6 [==============================] - 4s 11ms/step - loss: 0.7252 - accuracy: 0.5868
Epoch 2/500
6/6 [==============================] - 0s 10ms/step - loss: 0.7236 - accuracy: 0.5988
Epoch 3/500
6/6 [==============================] - 0s 9ms/step - loss: 0.7222 - accuracy: 0.6018
Epoch 4/500
6/6 [==============================] - 0s 8ms/step - loss: 0.7206 - accuracy: 0.6018
Epoch 5/500
6/6 [==============================] - 0s 7ms/step - loss: 0.7191 - accuracy: 0.6048
Epoch 6/500
6/6 [==============================] - 0s 6ms/step - loss: 0.7178 - accuracy: 0.6048
Epoch 7/500
6/6 [==============================] - 0s 5ms/step - loss: 0.7163 - accuracy: 0.6078
Epoch 8/500
6/6 [==============================] - 0s 6ms/step - loss: 0.7149 - accuracy: 0.6078
Epoch 9/500
6/6 [==============================] - 0s 5ms/step - loss: 0.7136 - accuracy: 0.6078
Epoch 10/500
6/6 [==============================] - 0s 4ms/step - loss: 0.7123 - accuracy: 0.6078
Epoch 11/500
6/6 [==============================] - 0s 4ms/step - loss: 0.7108 - accuracy: 0.6138
Epoch 12/500
6/6 [==============================] - 0s 5ms/step - loss: 0.7096 - accuracy: 0.6168
Epoch 13/500
6/6 [==============================] - 0s 6ms/step - loss: 0.7081 - accuracy: 0.6168
Epoch 14/500
6/6 [==============================] - 0s 7ms/step - loss: 0.7068 - accuracy: 0.6198
Epoch 15/500
6/6 [==============================] - 0s 8ms/step - loss: 0.7054 - accuracy: 0.6257
Epoch 16/500
6/6 [==============================] - 0s 6ms/step - loss: 0.7042 - accuracy: 0.6287
Epoch 17/500
6/6 [==============================] - 0s 5ms/step - loss: 0.7029 - accuracy: 0.6287
Epoch 18/500
6/6 [==============================] - 0s 6ms/step - loss: 0.7017 - accuracy: 0.6257
Epoch 19/500
6/6 [==============================] - 0s 6ms/step - loss: 0.7005 - accuracy: 0.6287
Epoch 20/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6992 - accuracy: 0.6317
Epoch 21/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6980 - accuracy: 0.6347
Epoch 22/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6967 - accuracy: 0.6347
Epoch 23/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6955 - accuracy: 0.6377
Epoch 24/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6942 - accuracy: 0.6407
Epoch 25/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6931 - accuracy: 0.6407
Epoch 26/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6919 - accuracy: 0.6467
Epoch 27/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6908 - accuracy: 0.6467
Epoch 28/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6896 - accuracy: 0.6467
Epoch 29/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6885 - accuracy: 0.6467
Epoch 30/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6875 - accuracy: 0.6467
Epoch 31/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6864 - accuracy: 0.6437
Epoch 32/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6855 - accuracy: 0.6407
Epoch 33/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6845 - accuracy: 0.6437
Epoch 34/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6835 - accuracy: 0.6407
Epoch 35/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6824 - accuracy: 0.6437
Epoch 36/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6814 - accuracy: 0.6497
Epoch 37/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6804 - accuracy: 0.6557
Epoch 38/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6795 - accuracy: 0.6707
Epoch 39/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6784 - accuracy: 0.6707
Epoch 40/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6775 - accuracy: 0.6707
Epoch 41/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6766 - accuracy: 0.6707
Epoch 42/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6757 - accuracy: 0.6737
Epoch 43/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6749 - accuracy: 0.6737
Epoch 44/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6741 - accuracy: 0.6737
Epoch 45/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6733 - accuracy: 0.6826
Epoch 46/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6725 - accuracy: 0.6796
Epoch 47/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6716 - accuracy: 0.6796
Epoch 48/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6709 - accuracy: 0.6826
Epoch 49/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6701 - accuracy: 0.6826
Epoch 50/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6693 - accuracy: 0.6856
Epoch 51/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6686 - accuracy: 0.6856
Epoch 52/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6678 - accuracy: 0.6856
Epoch 53/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6670 - accuracy: 0.6856
Epoch 54/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6664 - accuracy: 0.6856
Epoch 55/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6656 - accuracy: 0.6826
Epoch 56/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6648 - accuracy: 0.6826
Epoch 57/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6641 - accuracy: 0.6856
Epoch 58/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6634 - accuracy: 0.6886
Epoch 59/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6626 - accuracy: 0.6916
Epoch 60/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6621 - accuracy: 0.6916
Epoch 61/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6613 - accuracy: 0.6886
Epoch 62/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6607 - accuracy: 0.6856
Epoch 63/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6600 - accuracy: 0.6826
Epoch 64/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6594 - accuracy: 0.6856
Epoch 65/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6587 - accuracy: 0.6856
Epoch 66/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6581 - accuracy: 0.6856
Epoch 67/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6576 - accuracy: 0.6886
Epoch 68/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6570 - accuracy: 0.6886
Epoch 69/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6564 - accuracy: 0.6916
Epoch 70/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6558 - accuracy: 0.6886
Epoch 71/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6552 - accuracy: 0.6886
Epoch 72/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6547 - accuracy: 0.6916
Epoch 73/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6542 - accuracy: 0.6946
Epoch 74/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6535 - accuracy: 0.6946
Epoch 75/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6530 - accuracy: 0.6886
Epoch 76/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6525 - accuracy: 0.6886
Epoch 77/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6520 - accuracy: 0.6856
Epoch 78/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6515 - accuracy: 0.6826
Epoch 79/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6512 - accuracy: 0.6796
Epoch 80/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6507 - accuracy: 0.6796
Epoch 81/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6503 - accuracy: 0.6826
Epoch 82/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6498 - accuracy: 0.6826
Epoch 83/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6494 - accuracy: 0.6826
Epoch 84/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6490 - accuracy: 0.6826
Epoch 85/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6485 - accuracy: 0.6826
Epoch 86/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6481 - accuracy: 0.6796
Epoch 87/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6477 - accuracy: 0.6766
Epoch 88/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6473 - accuracy: 0.6766
Epoch 89/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6469 - accuracy: 0.6737
Epoch 90/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6464 - accuracy: 0.6737
Epoch 91/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6461 - accuracy: 0.6737
Epoch 92/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6457 - accuracy: 0.6707
Epoch 93/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6453 - accuracy: 0.6707
Epoch 94/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6449 - accuracy: 0.6707
Epoch 95/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6445 - accuracy: 0.6707
Epoch 96/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6441 - accuracy: 0.6707
Epoch 97/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6437 - accuracy: 0.6707
Epoch 98/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6433 - accuracy: 0.6737
Epoch 99/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6429 - accuracy: 0.6737
Epoch 100/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6425 - accuracy: 0.6737
Epoch 101/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6421 - accuracy: 0.6737
Epoch 102/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6418 - accuracy: 0.6737
Epoch 103/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6415 - accuracy: 0.6707
Epoch 104/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6411 - accuracy: 0.6707
Epoch 105/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6408 - accuracy: 0.6707
Epoch 106/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6406 - accuracy: 0.6677
Epoch 107/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6403 - accuracy: 0.6677
Epoch 108/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6399 - accuracy: 0.6677
Epoch 109/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6396 - accuracy: 0.6677
Epoch 110/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6394 - accuracy: 0.6677
Epoch 111/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6391 - accuracy: 0.6677
Epoch 112/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6388 - accuracy: 0.6677
Epoch 113/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6386 - accuracy: 0.6677
Epoch 114/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6383 - accuracy: 0.6677
Epoch 115/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6380 - accuracy: 0.6647
Epoch 116/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6378 - accuracy: 0.6647
Epoch 117/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6376 - accuracy: 0.6647
Epoch 118/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6373 - accuracy: 0.6647
Epoch 119/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6371 - accuracy: 0.6647
Epoch 120/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6368 - accuracy: 0.6647
Epoch 121/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6365 - accuracy: 0.6677
Epoch 122/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6363 - accuracy: 0.6677
Epoch 123/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6361 - accuracy: 0.6647
Epoch 124/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6359 - accuracy: 0.6647
Epoch 125/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6357 - accuracy: 0.6647
Epoch 126/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6355 - accuracy: 0.6647
Epoch 127/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6353 - accuracy: 0.6677
Epoch 128/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6352 - accuracy: 0.6647
Epoch 129/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6350 - accuracy: 0.6647
Epoch 130/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6348 - accuracy: 0.6677
Epoch 131/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6346 - accuracy: 0.6677
Epoch 132/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6344 - accuracy: 0.6677
Epoch 133/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6342 - accuracy: 0.6677
Epoch 134/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6340 - accuracy: 0.6677
Epoch 135/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6338 - accuracy: 0.6677
Epoch 136/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6336 - accuracy: 0.6677
Epoch 137/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6335 - accuracy: 0.6677
Epoch 138/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6333 - accuracy: 0.6677
Epoch 139/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6332 - accuracy: 0.6677
Epoch 140/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6330 - accuracy: 0.6677
Epoch 141/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6328 - accuracy: 0.6677
Epoch 142/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6326 - accuracy: 0.6677
Epoch 143/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6324 - accuracy: 0.6677
Epoch 144/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6323 - accuracy: 0.6677
Epoch 145/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6321 - accuracy: 0.6677
Epoch 146/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6320 - accuracy: 0.6677
Epoch 147/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6318 - accuracy: 0.6677
Epoch 148/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6316 - accuracy: 0.6677
Epoch 149/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6315 - accuracy: 0.6647
Epoch 150/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6313 - accuracy: 0.6647
Epoch 151/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6312 - accuracy: 0.6647
Epoch 152/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6311 - accuracy: 0.6647
Epoch 153/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6310 - accuracy: 0.6647
Epoch 154/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6309 - accuracy: 0.6647
Epoch 155/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6307 - accuracy: 0.6647
Epoch 156/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6306 - accuracy: 0.6677
Epoch 157/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6305 - accuracy: 0.6677
Epoch 158/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6304 - accuracy: 0.6677
Epoch 159/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6303 - accuracy: 0.6677
Epoch 160/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6302 - accuracy: 0.6677
Epoch 161/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6301 - accuracy: 0.6677
Epoch 162/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6300 - accuracy: 0.6677
Epoch 163/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6299 - accuracy: 0.6677
Epoch 164/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6298 - accuracy: 0.6677
Epoch 165/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6297 - accuracy: 0.6707
Epoch 166/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6296 - accuracy: 0.6707
Epoch 167/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6295 - accuracy: 0.6737
Epoch 168/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6295 - accuracy: 0.6737
Epoch 169/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6294 - accuracy: 0.6737
Epoch 170/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6292 - accuracy: 0.6737
Epoch 171/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6292 - accuracy: 0.6737
Epoch 172/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6291 - accuracy: 0.6737
Epoch 173/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6290 - accuracy: 0.6737
Epoch 174/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6288 - accuracy: 0.6707
Epoch 175/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6288 - accuracy: 0.6737
Epoch 176/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6286 - accuracy: 0.6737
Epoch 177/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6285 - accuracy: 0.6737
Epoch 178/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6284 - accuracy: 0.6737
Epoch 179/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6283 - accuracy: 0.6677
Epoch 180/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6282 - accuracy: 0.6677
Epoch 181/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6281 - accuracy: 0.6677
Epoch 182/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6281 - accuracy: 0.6677
Epoch 183/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6280 - accuracy: 0.6677
Epoch 184/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6279 - accuracy: 0.6677
Epoch 185/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6278 - accuracy: 0.6677
Epoch 186/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6278 - accuracy: 0.6707
Epoch 187/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6277 - accuracy: 0.6707
Epoch 188/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6276 - accuracy: 0.6707
Epoch 189/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6276 - accuracy: 0.6707
Epoch 190/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6275 - accuracy: 0.6707
Epoch 191/500
6/6 [==============================] - 0s 4ms/step - loss: 0.6275 - accuracy: 0.6707
Epoch 192/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6274 - accuracy: 0.6707
Epoch 193/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6274 - accuracy: 0.6677
Epoch 194/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6273 - accuracy: 0.6677
Epoch 195/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6273 - accuracy: 0.6677
Epoch 196/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6272 - accuracy: 0.6647
Epoch 197/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6272 - accuracy: 0.6677
Epoch 198/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6271 - accuracy: 0.6647
Epoch 199/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6271 - accuracy: 0.6647
Epoch 200/500
6/6 [==============================] - 0s 7ms/step - loss: 0.6270 - accuracy: 0.6647
Epoch 201/500
6/6 [==============================] - 0s 6ms/step - loss: 0.6270 - accuracy: 0.6647
Epoch 202/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6269 - accuracy: 0.6617
Epoch 203/500
6/6 [==============================] - 0s 5ms/step - loss: 0.6269 - accuracy: 0.6647

In [19]:
n_predict = single_n.predict(x_test_scaled)

3/3 [==============================] - 0s 5ms/step

In [20]:
n_predict = single_n.predict(x_test_scaled)

# Convert probabilities → 0 or 1
n_predict_binary = (n_predict > 0.5).astype(int).flatten()

print(precision_score(y_test, n_predict_binary))

3/3 [==============================] - 0s 2ms/step
0.5

In [21]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [22]:
import torch
import torch.nn as nn

# Check GPU
print(torch.cuda.is_available())  # Should print True
print(torch.cuda.get_device_name(0))  # Should show RTX 4050

ModuleNotFoundError: No module named 'torch'